"""Server-side PDF report generation with fpdf2.

This is the fallback for the browser export: it produces the same sections
without needing a rendered page, so a report can be generated from a job, a
retry, or a client whose canvas capture failed.
"""

from __future__ import annotations

import io
import logging
import re
from datetime import datetime, timezone
from typing import Any, Final

from fpdf import FPDF

logger = logging.getLogger(__name__)

# Letter grades. Boundaries chosen so the worked examples in the report spec
# hold: 82 -> A-, 78 -> B+, 74 -> B, 71 -> B, 65 -> C+.
# Mirrored in frontend/src/utils/scoreCalculator.js - change both together.
GRADE_BANDS: Final[list[tuple[float, str]]] = [
    (90, "A+"),
    (85, "A"),
    (80, "A-"),
    (76, "B+"),
    (70, "B"),
    (66, "B-"),
    (62, "C+"),
    (56, "C"),
    (50, "C-"),
    (40, "D"),
    (0, "F"),
]

WATERMARK: Final[str] = "Generated by ARIA AI"

# Palette, converted to the light document the PDF actually prints on. The
# on-screen theme is dark; a dark PDF wastes ink and reads badly when shared.
INK = (26, 32, 44)
MUTED = (110, 122, 145)
RULE = (222, 228, 238)
BLUE = (45, 125, 210)
GREEN = (16, 133, 96)
AMBER = (176, 116, 8)
RED = (198, 54, 54)

ROLE_LABELS: Final[dict[str, str]] = {
    "data_analyst": "Data Analyst",
    "software_engineer": "Software Engineer",
    "hr": "Human Resources",
    "ai_engineer": "AI Engineer",
}

# fpdf2's core fonts are Latin-1 only. Whisper happily returns smart quotes and
# dashes, which would raise on output, so they are folded to ASCII rather than
# shipping a TTF with the app.
_UNICODE_FOLD = {
    "‘": "'", "’": "'", "“": '"', "”": '"',
    "–": "-", "—": "-", "…": "...", " ": " ",
    "•": "-", "→": "->", "·": "-",
}


def latin1(text: Any) -> str:
    """Make text safe for fpdf2's built-in fonts."""
    s = "" if text is None else str(text)
    for bad, good in _UNICODE_FOLD.items():
        s = s.replace(bad, good)
    s = re.sub(r"\s+", " ", s).strip()
    return s.encode("latin-1", "replace").decode("latin-1")


def grade_for(score: float | None) -> str:
    """Letter grade for a 0-100 score. '-' when unscored."""
    if score is None:
        return "-"
    for threshold, letter in GRADE_BANDS:
        if score >= threshold:
            return letter
    return "F"


def _score_colour(score: float | None) -> tuple[int, int, int]:
    if score is None:
        return MUTED
    if score > 75:
        return GREEN
    if score >= 50:
        return AMBER
    return RED


class ReportPDF(FPDF):
    """A4 report with a running footer watermark."""

    def header(self) -> None:
        # Every page starts at the left margin. The footer writes right-aligned
        # cells, which leave x at the right edge; without this reset the first
        # multi_cell after an automatic page break sees zero usable width and
        # raises "Not enough horizontal space to render a single character".
        self.set_xy(self.l_margin, self.t_margin)

    def footer(self) -> None:
        # The footer runs mid-flow when auto page break fires, so the cursor and
        # font are saved and restored. Without this it leaves x at the right
        # margin and the first multi_cell on the new page raises
        # "Not enough horizontal space to render a single character".
        saved = (self.x, self.y, self.font_family, self.font_style, self.font_size_pt)

        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*MUTED)
        self.cell(0, 6, f"Page {self.page_no()}", align="L")
        self.set_y(-12)
        # Bottom right on every page, per the report spec.
        self.cell(0, 6, latin1(WATERMARK), align="R")

        self.set_xy(saved[0], saved[1])
        self.set_font(saved[2], saved[3], saved[4])


class ReportService:
    """Builds the PDF interview report."""

    MARGIN = 16

    # fpdf2 leaves the cursor wherever the previous cell ended, and a
    # right-aligned footer cell parks it at the right edge. A full-width
    # multi_cell then sees zero usable width and raises. Every full-width write
    # goes through these helpers, which anchor x to the left margin first.
    @staticmethod
    def _para(pdf: FPDF, height: float, text: str) -> None:
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, height, text)

    @staticmethod
    def _line(pdf: FPDF, height: float, text: str) -> None:
        pdf.set_x(pdf.l_margin)
        pdf.cell(0, height, text, new_x="LMARGIN", new_y="NEXT")

    def generate_pdf(
        self,
        session: Any,
        answers: list,
        user: Any,
        history: list | None = None,
    ) -> bytes:
        """Render the whole report and return the PDF bytes."""
        pdf = ReportPDF(orientation="P", unit="mm", format="A4")
        pdf.set_auto_page_break(auto=True, margin=18)
        pdf.set_margins(self.MARGIN, self.MARGIN, self.MARGIN)
        pdf.set_title(latin1("ARIA AI Interview Performance Report"))
        pdf.set_author(latin1("ARIA AI"))
        pdf.add_page()

        feedback = session.final_feedback or {}
        self._header(pdf, session, user)
        self._executive_summary(pdf, session, feedback)
        self._score_table(pdf, session)
        self._question_analysis(pdf, answers)
        self._bullets(pdf, "Strengths", feedback.get("strengths") or [], GREEN)
        self._bullets(pdf, "Improvement Areas", feedback.get("weaknesses") or [], AMBER)
        self._next_steps(pdf, feedback)
        self._history(pdf, history or [], session)

        out = pdf.output()
        return bytes(out)

    # ---- Sections -------------------------------------------------------- #
    def _rule(self, pdf: FPDF, gap: float = 3.0) -> None:
        pdf.ln(gap)
        pdf.set_draw_color(*RULE)
        pdf.set_line_width(0.2)
        y = pdf.get_y()
        pdf.line(self.MARGIN, y, pdf.w - self.MARGIN, y)
        pdf.ln(gap)

    def _section_title(self, pdf: FPDF, text: str, colour=INK) -> None:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(*colour)
        self._line(pdf, 7, latin1(text))
        pdf.ln(1)

    def _header(self, pdf: FPDF, session: Any, user: Any) -> None:
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(*BLUE)
        self._line(pdf, 10, "ARIA AI")

        pdf.set_font("Helvetica", "", 14)
        pdf.set_text_color(*INK)
        self._line(pdf, 8, "Interview Performance Report")

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*MUTED)
        when = session.completed_at or session.created_at or datetime.now(timezone.utc)
        name = getattr(user, "full_name", None) or getattr(user, "username", "Candidate")
        self._line(pdf, 6, latin1(f"{name}  |  {when:%d %B %Y}"))
        self._rule(pdf)

    def _executive_summary(self, pdf: FPDF, session: Any, feedback: dict) -> None:
        self._section_title(pdf, "Executive Summary")

        overall = session.overall_score
        pdf.set_font("Helvetica", "B", 34)
        pdf.set_text_color(*_score_colour(overall))
        score_text = f"{round(overall)}" if overall is not None else "--"
        pdf.cell(30, 16, latin1(score_text))

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*MUTED)
        self._line(pdf, 16, latin1(f"/ 100    Grade {grade_for(overall)}"))

        role = ROLE_LABELS.get(session.job_role, session.job_role)
        duration = (
            f"{session.duration_minutes} mins" if session.duration_minutes else "Duration unknown"
        )
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*INK)
        self._line(
            pdf, 6,
            latin1(f"Role: {role}   |   Difficulty: {session.difficulty}   |   Duration: {duration}"),
        )
        pdf.ln(2)

        verdict = feedback.get("overall_verdict")
        if verdict:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*INK)
            self._para(pdf, 5.2, latin1(verdict))
        self._rule(pdf)

    def _score_table(self, pdf: FPDF, session: Any) -> None:
        self._section_title(pdf, "Score Breakdown")

        rows = [
            ("Answer Quality", session.answer_score),
            ("Confidence", session.confidence_score),
            ("Communication", session.communication_score),
            ("Filler Words", session.filler_word_score),
            ("Overall", session.overall_score),
        ]
        widths = (86, 46, 46)

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*MUTED)
        pdf.set_fill_color(245, 247, 251)
        pdf.set_x(pdf.l_margin)
        for label, width in zip(("Metric", "Score", "Grade"), widths):
            pdf.cell(width, 8, latin1(label), border=0, fill=True)
        pdf.ln()

        for i, (label, value) in enumerate(rows):
            is_total = label == "Overall"
            pdf.set_font("Helvetica", "B" if is_total else "", 10)
            pdf.set_text_color(*INK)
            pdf.set_x(pdf.l_margin)
            pdf.cell(widths[0], 8, latin1(label), border="T")
            pdf.set_text_color(*_score_colour(value))
            shown = f"{round(value)}/100" if value is not None else "--"
            pdf.cell(widths[1], 8, latin1(shown), border="T")
            pdf.cell(widths[2], 8, latin1(grade_for(value)), border="T")
            pdf.ln()
        self._rule(pdf)

    def _question_analysis(self, pdf: FPDF, answers: list) -> None:
        self._section_title(pdf, "Detailed Question Analysis")

        if not answers:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*MUTED)
            self._para(pdf, 5, "No answers were recorded for this session.")
            self._rule(pdf)
            return

        for answer in answers:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*INK)
            pdf.multi_cell(
                0, 5.4, latin1(f"Q{answer.question_number}. {answer.question_text}")
            )
            pdf.ln(1)

            # First 100 words, as specified - a full transcript would run for pages.
            words = (answer.transcript or "").split()
            excerpt = " ".join(words[:100]) + ("..." if len(words) > 100 else "")
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*MUTED)
            self._para(pdf, 4.8, latin1(excerpt or "(no answer recorded)"))
            pdf.ln(1)

            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*INK)
            parts = [
                f"Answer {round(answer.answer_score)}" if answer.answer_score is not None else "Answer --",
                f"Confidence {round(answer.confidence_score)}" if answer.confidence_score is not None else "Confidence --",
                f"Communication {round(answer.communication_score)}" if answer.communication_score is not None else "Communication --",
                f"Fillers {answer.filler_count or 0}",
            ]
            self._line(pdf, 5, latin1("   |   ".join(parts)))

            if answer.ai_feedback:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*BLUE)
                self._para(pdf, 4.8, latin1(f"Feedback: {answer.ai_feedback}"))
            pdf.ln(3)

        self._rule(pdf)

    def _bullets(self, pdf: FPDF, title: str, items: list, colour) -> None:
        self._section_title(pdf, title, colour)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*INK)
        if not items:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*MUTED)
            self._para(pdf, 5, latin1("Nothing recorded."))
        for item in items[:3]:
            self._para(pdf, 5.2, latin1(f"-  {item}"))
            pdf.ln(0.5)
        self._rule(pdf)

    def _next_steps(self, pdf: FPDF, feedback: dict) -> None:
        steps = list(feedback.get("top_suggestions") or [])
        resources = list(feedback.get("recommended_resources") or [])
        if not steps and not resources:
            return

        self._section_title(pdf, "Recommended Next Steps")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*INK)
        for step in steps[:3]:
            self._para(pdf, 5.2, latin1(f"-  {step}"))
            pdf.ln(0.5)

        if resources:
            pdf.ln(1)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*MUTED)
            self._line(pdf, 6, "Worth studying")
            pdf.set_font("Helvetica", "", 9.5)
            pdf.set_text_color(*INK)
            for resource in resources[:3]:
                self._para(pdf, 5, latin1(f"-  {resource}"))
        self._rule(pdf)

    def _history(self, pdf: FPDF, history: list, current: Any) -> None:
        """Last five sessions. Omitted entirely when this is the only one."""
        rows = [s for s in history if s.overall_score is not None][:5]
        if len(rows) < 2:
            return

        self._section_title(pdf, "Progress History")
        widths = (46, 52, 34, 24, 22)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*MUTED)
        pdf.set_fill_color(245, 247, 251)
        pdf.set_x(pdf.l_margin)
        for label, width in zip(("Date", "Role", "Difficulty", "Score", "Grade"), widths):
            pdf.cell(width, 8, latin1(label), fill=True)
        pdf.ln()

        for s in rows:
            when = s.completed_at or s.created_at
            is_current = str(s.id) == str(current.id)
            pdf.set_font("Helvetica", "B" if is_current else "", 9)
            pdf.set_text_color(*INK)
            pdf.set_x(pdf.l_margin)
            pdf.cell(widths[0], 7, latin1(f"{when:%d %b %Y}" if when else "-"), border="T")
            pdf.cell(widths[1], 7, latin1(ROLE_LABELS.get(s.job_role, s.job_role)), border="T")
            pdf.cell(widths[2], 7, latin1(s.difficulty), border="T")
            pdf.set_text_color(*_score_colour(s.overall_score))
            pdf.cell(widths[3], 7, latin1(f"{round(s.overall_score)}"), border="T")
            pdf.cell(widths[4], 7, latin1(grade_for(s.overall_score)), border="T")
            pdf.ln()

    @staticmethod
    def filename_for(session: Any) -> str:
        """ARIA_Report_[role]_[date].pdf"""
        when = session.completed_at or session.created_at or datetime.now(timezone.utc)
        role = ROLE_LABELS.get(session.job_role, session.job_role or "interview")
        slug = re.sub(r"[^A-Za-z0-9]+", "_", role).strip("_")
        return f"ARIA_Report_{slug}_{when:%Y-%m-%d}.pdf"


report_service = ReportService()

__all__ = ["ReportService", "report_service", "grade_for", "GRADE_BANDS", "WATERMARK"]
