// Shareable interview report.
//
// Rendered on a white sheet rather than in the app's dark theme: this document
// is meant to be printed, exported and sent to someone, and a dark PDF is both
// hard to read on paper and wasteful to print. The dark chrome stays around it.

import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { AlertCircle, ArrowLeft, Download, FileDown, Printer, RefreshCw } from 'lucide-react'

import useAuth from '../hooks/useAuth'
import { reportApi, sessionsApi, extractErrorMessage } from '../services/api'
import { Button, LoadingSpinner } from '../components/ui'
import { gradeFor } from '../utils/scoreCalculator'
import useToast from '../store/toastStore'

const ROLE_LABELS = {
  data_analyst: 'Data Analyst',
  software_engineer: 'Software Engineer',
  hr: 'Human Resources',
  ai_engineer: 'AI Engineer',
}

const WATERMARK = 'Generated by ARIA AI'

const dateFmt = new Intl.DateTimeFormat(undefined, {
  day: 'numeric',
  month: 'long',
  year: 'numeric',
})
const shortDate = new Intl.DateTimeFormat(undefined, {
  day: '2-digit',
  month: 'short',
  year: 'numeric',
})

// Print/PDF palette. Deliberately not the aria-* tokens: those are tuned for a
// dark background and several of them fail contrast on white.
const INK = '#1A202C'
const MUTED = '#6E7A91'
const RULE = '#DEE4EE'

function scoreColour(value) {
  if (value === null || value === undefined) return MUTED
  if (value > 75) return '#108560'
  if (value >= 50) return '#B07408'
  return '#C63636'
}

const fmtScore = (v) => (v === null || v === undefined ? '--' : `${Math.round(v)}/100`)

/** Build ARIA_Report_[role]_[date].pdf, matching the server's naming. */
function pdfFilename(session) {
  const when = new Date(session.completed_at || session.created_at || Date.now())
  const role = (ROLE_LABELS[session.job_role] ?? session.job_role ?? 'Interview').replace(
    /[^A-Za-z0-9]+/g,
    '_',
  )
  const iso = `${when.getFullYear()}-${String(when.getMonth() + 1).padStart(2, '0')}-${String(when.getDate()).padStart(2, '0')}`
  return `ARIA_Report_${role}_${iso}.pdf`
}

export default function Report() {
  const { sessionId } = useParams()
  const navigate = useNavigate()
  const user = useAuth((s) => s.user)
  const toastSuccess = useToast((s) => s.success)
  const toastError = useToast((s) => s.error)

  const [session, setSession] = useState(null)
  const [history, setHistory] = useState([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState(null)
  const [isExporting, setIsExporting] = useState(false)

  const sheetRef = useRef(null)
  const abortRef = useRef(null)

  const load = useCallback(async () => {
    setIsLoading(true)
    setError(null)
    abortRef.current?.abort()
    abortRef.current = new AbortController()
    const { signal } = abortRef.current
    try {
      let data = await sessionsApi.get(sessionId, { signal })
      if (!data.final_feedback) {
        data = await sessionsApi.complete(sessionId, { signal })
      }
      setSession(data)
      const all = await sessionsApi.mySessions({ signal })
      setHistory(
        all
          .filter((s) => typeof s.overall_score === 'number')
          .sort((a, b) => new Date(b.created_at) - new Date(a.created_at))
          .slice(0, 5),
      )
    } catch (err) {
      if (err?.code === 'ERR_CANCELED' || err?.name === 'CanceledError') return
      setError(extractErrorMessage(err, 'Could not load this report.'))
    } finally {
      setIsLoading(false)
    }
  }, [sessionId])

  useEffect(() => {
    // oxlint-disable-next-line react/set-state-in-effect
    load()
    return () => abortRef.current?.abort()
  }, [load])

  const saveBlob = (blob, filename) => {
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    link.remove()
    // Revoking immediately can cancel the download in some browsers.
    setTimeout(() => URL.revokeObjectURL(url), 2000)
  }

  /** Client-side export: capture the sheet, slice it across A4 pages. */
  const handleDownloadPdf = async () => {
    if (!sheetRef.current) return
    setIsExporting(true)
    try {
      // Loaded on demand: together these are ~350kB and only matter when
      // someone actually exports.
      const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
        import('html2canvas'),
        import('jspdf'),
      ])

      const canvas = await html2canvas(sheetRef.current, {
        scale: 2,
        backgroundColor: '#ffffff',
        logging: false,
        useCORS: true,
      })

      const pdf = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' })
      const pageW = pdf.internal.pageSize.getWidth()
      const pageH = pdf.internal.pageSize.getHeight()
      const margin = 10
      const imgW = pageW - margin * 2
      const imgH = (canvas.height * imgW) / canvas.width
      const usableH = pageH - margin * 2
      const image = canvas.toDataURL('image/jpeg', 0.94)

      const stamp = () => {
        pdf.setFontSize(7)
        pdf.setTextColor(140, 148, 165)
        pdf.text(WATERMARK, pageW - margin, pageH - 5, { align: 'right' })
      }

      // The capture is one tall image; each page shows a different slice of it
      // by shifting the y offset, which is why position goes negative.
      let remaining = imgH
      let position = margin
      pdf.addImage(image, 'JPEG', margin, position, imgW, imgH)
      stamp()
      remaining -= usableH

      while (remaining > 0) {
        position = margin - (imgH - remaining)
        pdf.addPage()
        pdf.addImage(image, 'JPEG', margin, position, imgW, imgH)
        stamp()
        remaining -= usableH
      }

      pdf.save(pdfFilename(session))
      toastSuccess('Report downloaded', pdfFilename(session))
    } catch (err) {
      toastError(
        'Could not build the PDF here',
        'Try "Server PDF", which renders it on the backend instead.',
      )
      console.error('Client PDF export failed:', err)
    } finally {
      setIsExporting(false)
    }
  }

  /** Server-rendered PDF: works even if the canvas capture fails. */
  const handleServerPdf = async () => {
    setIsExporting(true)
    try {
      const { blob, filename } = await reportApi.pdf(sessionId)
      saveBlob(blob, filename)
      toastSuccess('Report downloaded', filename)
    } catch (err) {
      toastError('Could not generate the PDF', extractErrorMessage(err))
    } finally {
      setIsExporting(false)
    }
  }

  if (isLoading) {
    return (
      <div className="grid min-h-[60vh] place-items-center">
        <LoadingSpinner size="md" showLabel label="Building your report" />
      </div>
    )
  }

  if (error || !session) {
    return (
      <div className="mx-auto max-w-md py-16 text-center">
        <AlertCircle className="mx-auto h-8 w-8 text-aria-red" aria-hidden="true" />
        <h1 className="mt-4 font-display text-xl font-semibold">Could not load this report</h1>
        <p className="mt-2 text-sm text-aria-muted">{error}</p>
        <div className="mt-6 flex justify-center gap-3">
          <Button onClick={load} leftIcon={<RefreshCw className="h-4 w-4" />}>
            Try again
          </Button>
          <Button variant="outline" onClick={() => navigate('/')}>
            Dashboard
          </Button>
        </div>
      </div>
    )
  }

  const feedback = session.final_feedback ?? {}
  const answers = [...(session.answers ?? [])].sort(
    (a, b) => a.question_number - b.question_number,
  )
  const when = new Date(session.completed_at || session.created_at)
  const rows = [
    ['Answer Quality', session.answer_score],
    ['Confidence', session.confidence_score],
    ['Communication', session.communication_score],
    ['Filler Words', session.filler_word_score],
    ['Overall', session.overall_score],
  ]

  return (
    <div className="mx-auto max-w-4xl">
      {/* Toolbar - excluded from print and from the canvas capture. */}
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3 print:hidden">
        <Button
          variant="ghost"
          onClick={() => navigate(`/analysis/${sessionId}`)}
          leftIcon={<ArrowLeft className="h-4 w-4" />}
        >
          Back to analysis
        </Button>
        <div className="flex flex-wrap gap-2">
          <Button variant="ghost" onClick={() => window.print()} leftIcon={<Printer className="h-4 w-4" />}>
            Print
          </Button>
          <Button
            variant="outline"
            onClick={handleServerPdf}
            isLoading={isExporting}
            leftIcon={<FileDown className="h-4 w-4" />}
          >
            Server PDF
          </Button>
          <Button
            onClick={handleDownloadPdf}
            isLoading={isExporting}
            leftIcon={<Download className="h-4 w-4" />}
          >
            Download PDF
          </Button>
        </div>
      </div>

      {/* ---- The document sheet -------------------------------------------- */}
      <div
        ref={sheetRef}
        className="report-sheet relative mx-auto w-full rounded-lg bg-white p-8 shadow-surface sm:p-12 print:rounded-none print:p-0 print:shadow-none"
        style={{ color: INK }}
      >
        {/* Header */}
        <header className="flex flex-wrap items-start justify-between gap-4 pb-5" style={{ borderBottom: `1px solid ${RULE}` }}>
          <div>
            <p className="font-display text-2xl font-bold" style={{ color: '#2D7DD2' }}>
              ARIA AI
            </p>
            <h1 className="mt-1 font-display text-xl font-semibold">
              Interview Performance Report
            </h1>
          </div>
          <div className="text-right text-sm" style={{ color: MUTED }}>
            <p className="font-medium" style={{ color: INK }}>
              {user?.full_name || user?.username || 'Candidate'}
            </p>
            <p>{dateFmt.format(when)}</p>
          </div>
        </header>

        {/* Executive summary */}
        <section className="py-6" style={{ borderBottom: `1px solid ${RULE}` }}>
          <h2 className="mb-3 font-display text-base font-bold">Executive Summary</h2>
          <div className="flex flex-wrap items-baseline gap-3">
            <span
              className="font-mono text-5xl font-bold tabular-nums"
              style={{ color: scoreColour(session.overall_score) }}
            >
              {session.overall_score !== null ? Math.round(session.overall_score) : '--'}
            </span>
            <span className="text-sm" style={{ color: MUTED }}>
              / 100 &nbsp; Grade {gradeFor(session.overall_score)}
            </span>
          </div>
          <p className="mt-3 text-sm">
            <span style={{ color: MUTED }}>Role:</span>{' '}
            {ROLE_LABELS[session.job_role] ?? session.job_role}
            <span style={{ color: RULE }}> &nbsp;|&nbsp; </span>
            <span style={{ color: MUTED }}>Difficulty:</span> {session.difficulty}
            <span style={{ color: RULE }}> &nbsp;|&nbsp; </span>
            <span style={{ color: MUTED }}>Duration:</span>{' '}
            {session.duration_minutes ? `${session.duration_minutes} mins` : 'unknown'}
          </p>
          {feedback.overall_verdict ? (
            <p className="mt-4 text-sm leading-relaxed">{feedback.overall_verdict}</p>
          ) : null}
        </section>

        {/* Score breakdown */}
        <section className="py-6" style={{ borderBottom: `1px solid ${RULE}` }}>
          <h2 className="mb-3 font-display text-base font-bold">Score Breakdown</h2>
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr style={{ background: '#F5F7FB', color: MUTED }}>
                <th scope="col" className="p-2 text-left font-medium">Metric</th>
                <th scope="col" className="p-2 text-left font-medium">Score</th>
                <th scope="col" className="p-2 text-left font-medium">Grade</th>
              </tr>
            </thead>
            <tbody>
              {rows.map(([label, value]) => (
                <tr key={label} style={{ borderTop: `1px solid ${RULE}` }}>
                  <td className={`p-2 ${label === 'Overall' ? 'font-semibold' : ''}`}>{label}</td>
                  <td
                    className="p-2 font-mono tabular-nums"
                    style={{ color: scoreColour(value), fontWeight: label === 'Overall' ? 700 : 400 }}
                  >
                    {fmtScore(value)}
                  </td>
                  <td className={`p-2 font-mono ${label === 'Overall' ? 'font-bold' : ''}`}>
                    {gradeFor(value)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {/* Question analysis */}
        <section className="py-6" style={{ borderBottom: `1px solid ${RULE}` }}>
          <h2 className="mb-3 font-display text-base font-bold">Detailed Question Analysis</h2>
          {answers.length ? (
            <ol className="space-y-5">
              {answers.map((a) => {
                const words = (a.transcript || '').split(/\s+/).filter(Boolean)
                const excerpt = words.slice(0, 100).join(' ') + (words.length > 100 ? '…' : '')
                return (
                  <li key={a.id} className="break-inside-avoid">
                    <p className="text-sm font-semibold">
                      Q{a.question_number}. {a.question_text}
                    </p>
                    <p className="mt-1.5 text-sm italic leading-relaxed" style={{ color: MUTED }}>
                      {excerpt || '(no answer recorded)'}
                    </p>
                    <p className="mt-1.5 font-mono text-xs">
                      Answer {a.answer_score != null ? Math.round(a.answer_score) : '--'}
                      {'  |  '}Confidence {a.confidence_score != null ? Math.round(a.confidence_score) : '--'}
                      {'  |  '}Communication {a.communication_score != null ? Math.round(a.communication_score) : '--'}
                      {'  |  '}Fillers {a.filler_count ?? 0}
                    </p>
                    {a.ai_feedback ? (
                      <p className="mt-1.5 text-sm leading-relaxed" style={{ color: '#2D7DD2' }}>
                        {a.ai_feedback}
                      </p>
                    ) : null}
                  </li>
                )
              })}
            </ol>
          ) : (
            <p className="text-sm" style={{ color: MUTED }}>
              No answers were recorded for this session.
            </p>
          )}
        </section>

        {/* Strengths / improvements */}
        <section className="py-6" style={{ borderBottom: `1px solid ${RULE}` }}>
          <h2 className="mb-2 font-display text-base font-bold" style={{ color: '#108560' }}>
            Strengths
          </h2>
          {feedback.strengths?.length ? (
            <ul className="ml-4 list-disc space-y-1.5 text-sm">
              {feedback.strengths.slice(0, 3).map((s, i) => <li key={i}>{s}</li>)}
            </ul>
          ) : (
            <p className="text-sm" style={{ color: MUTED }}>Nothing recorded.</p>
          )}

          <h2 className="mb-2 mt-6 font-display text-base font-bold" style={{ color: '#B07408' }}>
            Improvement Areas
          </h2>
          {feedback.weaknesses?.length ? (
            <ul className="ml-4 list-disc space-y-1.5 text-sm">
              {feedback.weaknesses.slice(0, 3).map((s, i) => <li key={i}>{s}</li>)}
            </ul>
          ) : (
            <p className="text-sm" style={{ color: MUTED }}>Nothing recorded.</p>
          )}
        </section>

        {/* Next steps */}
        {feedback.top_suggestions?.length || feedback.recommended_resources?.length ? (
          <section className="py-6" style={{ borderBottom: `1px solid ${RULE}` }}>
            <h2 className="mb-3 font-display text-base font-bold">Recommended Next Steps</h2>
            <ul className="ml-4 list-disc space-y-1.5 text-sm">
              {(feedback.top_suggestions ?? []).slice(0, 3).map((s, i) => <li key={i}>{s}</li>)}
            </ul>
            {feedback.recommended_resources?.length ? (
              <>
                <p className="mb-1.5 mt-4 text-xs font-semibold uppercase tracking-wider" style={{ color: MUTED }}>
                  Worth studying
                </p>
                <ul className="ml-4 list-disc space-y-1 text-sm">
                  {feedback.recommended_resources.slice(0, 3).map((r, i) => <li key={i}>{r}</li>)}
                </ul>
              </>
            ) : null}
          </section>
        ) : null}

        {/* Progress history - only meaningful with more than one scored session */}
        {history.length >= 2 ? (
          <section className="py-6">
            <h2 className="mb-3 font-display text-base font-bold">Progress History</h2>
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr style={{ background: '#F5F7FB', color: MUTED }}>
                  <th scope="col" className="p-2 text-left font-medium">Date</th>
                  <th scope="col" className="p-2 text-left font-medium">Role</th>
                  <th scope="col" className="p-2 text-left font-medium">Difficulty</th>
                  <th scope="col" className="p-2 text-left font-medium">Score</th>
                  <th scope="col" className="p-2 text-left font-medium">Grade</th>
                </tr>
              </thead>
              <tbody>
                {history.map((s) => (
                  <tr
                    key={s.id}
                    style={{ borderTop: `1px solid ${RULE}` }}
                    className={s.id === sessionId ? 'font-semibold' : ''}
                  >
                    <td className="p-2">{shortDate.format(new Date(s.completed_at || s.created_at))}</td>
                    <td className="p-2">{ROLE_LABELS[s.job_role] ?? s.job_role}</td>
                    <td className="p-2">{s.difficulty}</td>
                    <td className="p-2 font-mono tabular-nums" style={{ color: scoreColour(s.overall_score) }}>
                      {Math.round(s.overall_score)}
                    </td>
                    <td className="p-2 font-mono">{gradeFor(s.overall_score)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        ) : null}

        {/* Watermark, bottom right of the sheet. The PDF exports add their own
            per-page copy, since this one only appears once. */}
        <p className="pt-6 text-right text-[10px] italic" style={{ color: MUTED }}>
          {WATERMARK}
        </p>
      </div>
    </div>
  )
}
